schema_version: 1

context:
  version: 1.28.1

recipe:
  name: c-ares
  version: ${{ version }}

source:
  url: https://c-ares.haxx.se/download/c-ares-${{ version }}.tar.gz
  sha256: 675a69fc54ddbf42e6830bc671eeb6cd89eeca43828eb413243fd2c0a760809d

build:
  number: 0

outputs:
  - package:
      name: c-ares
    build:
    requirements:
      build:
        - ${{ compiler("c") }}
        - if: win
          then: cmake
        # cmake on unix depends on c-ares. This breaks the cycle.
        - if: unix
          then: cmake-no-system
        - if: unix
          then: ninja
      
      run_exports:
        - ${{ pin_subpackage("c-ares", max_pin="x") }}
    tests:
      - script:
          - if: not win
            then: test -f ${PREFIX}/include/ares.h
          - if: not win
            then: test -f ${PREFIX}/lib/libcares${SHLIB_EXT}
          - if: not win
            then: test ! -f ${PREFIX}/lib/libcares.a
          - if: not win
            then: test ! -f ${PREFIX}/lib/libcares_static.a
          - if: win
            then: if not exist %PREFIX%\\Library\\include\\ares.h exit 1
          - if: win
            then: if not exist %PREFIX%\\Library\\bin\\cares.dll exit 1
          - if: win
            then: if not exist %PREFIX%\\Library\\lib\\cares.lib exit 1
          - if: win
            then: if exist %PREFIX%\\Library\\lib\\cares_static.lib exit 1
    script: build_output.sh  # [unix]
    script: bld_output.bat  # [win]
  - package:
      name: c-ares-static
    requirements:
      build:
        - ${{ compiler("c") }}
        - if: win
          then: cmake
        # cmake on unix depends on c-ares. This breaks the cycle.
        - if: unix
          then: cmake-no-system
        - if: unix
          then: ninja
      run_constraint:
        - c-ares <0a0
    tests:
      - script:
          - if: not win
            then: test -f ${PREFIX}/lib/libcares.a
          - if: not win
            then: test ! -f ${PREFIX}/lib/libcares${SHLIB_EXT}
          - if: not win
            then: test -f ${PREFIX}/include/ares.h
          - if: win
            then: if not exist %PREFIX%\\Library\\include\\ares.h exit 1
          - if: win
            then: if exist %PREFIX%\\Library\\bin\\cares.dll exit 1
          - if: win
            then: if not exist %PREFIX%\\Library\\lib\\cares.lib exit 1
    script: build_output.sh  # [unix]
    script: bld_output.bat  # [win]

about:
  license: MIT
  license_file: LICENSE.md
  summary: This is c-ares, an asynchronous resolver library
  homepage: https://c-ares.haxx.se/

extra:
  recipe-maintainers:
    - ocefpaf
    - wesm
    - xhochy
