local:
- path: recipes/boltons/recipe.yaml
- path: recipes/fastapi/recipe.yaml
- path: recipes/pip/recipe.yaml
- path: recipes/pthread-stubs/recipe.yaml
- path: recipes/zlib/recipe.yaml
- path: recipes/ca-certificates/recipe.yaml
- path: recipes/conda/recipe.yaml
- path: recipes/setuptools/recipe.yaml
- path: recipes/pytz/recipe.yaml
- path: recipes/six/recipe.yaml
- path: recipes/python-dateutil/recipe.yaml
- path: recipes/libpng/recipe.yaml
- path: recipes/freetype/recipe.yaml
- path: recipes/xz/recipe.yaml
- path: recipes/libffi/recipe.yaml
- path: recipes/_libgcc_mutex/recipe.yaml
- path: recipes/lerc/recipe.yaml
- path: recipes/tomli/recipe.yaml
- path: recipes/pyparsing/recipe.yaml
- path: recipes/pixman/recipe.yaml
- path: recipes/fonts-conda-forge/recipe.yaml
- path: recipes/fonts-conda-ecosystem/recipe.yaml
- path: recipes/cycler/recipe.yaml
- path: recipes/font-ttf-source-code-pro/recipe.yaml
- path: recipes/font-ttf-inconsolata/recipe.yaml
- path: recipes/font-ttf-ubuntu/recipe.yaml
- path: recipes/xorg-kbproto/recipe.yaml
# - path: recipes/jpeg/recipe.yaml # 9e invalid version
# - path: recipes/_openmp_mutex/recipe.yaml # broken pin_subpackage and recipe
# - path: recipes/libnsl/recipe.yaml # skiped on linux
#- path: recipes/pcre2/recipe.yaml # bad recipe converter outputs
#- path: recipes/brotli/recipe.yaml # bad recipe
# - path: recipes/kiwisolver/recipe.yaml skipped on linux
# - path: recipes/font-ttf-dejavu-sans-mono/recipe.yaml # bad checksum after downloading
# - path: recipes/munkres/recipe.yaml # fails to run the tests ( import munkres missing)
# - path: recipes/toml/recipe.yaml # fail to run tests ( import toml )
#- path: recipes/sqlite/recipe.yaml # bad conversion of multiple outputs
# - path: recipes/zlib/recipe.yaml # wrong conversion
# - path: recipes/wheel/recipe.yaml # license filesystem error
rattler-build:
  rev: 6f2c48e6e490967f3c47253c092853ee8fce9d57
  url: https://github.com/prefix-dev/rattler-build.git
repositories:
- branch: main
  recipes:
  - path: examples/rich/recipe.yaml
  - path: examples/curl/recipe.yaml
  url: https://github.com/prefix-dev/rattler-build.git
