[project]
name = "reproducible-builds-rattler-build"
version = "0.1.0"
description = "Add a short description here"
authors = ["nichmor <nmorkotilo@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "win-64"]

[tasks]
# Rewrite the readme with the updated data
rewrite-readme = "python src/repror/rewrite_readme.py"
# Used to generate build matrix for github
generate-recipes = "python src/repror/generate_recipes.py"
# Used to generate one matrix for github
generate-one-recipe = {cmd = "python src/repror/generate_recipes.py only_one > recipe.json", outputs = ["recipe.json"]}
# Build recipes using rattler-build for the current platform
build-all-recipes = "rattler-build build --recipe-dir recipes --output-dir recipes/outputs"
# Build a single recipe using the python script
build-recipe = "python src/repror/build_recipe.py"
# build a local recipe
build-local-recipe = { cmd = "cat recipe.json | python src/repror/build_recipe.py", depends-on = ["generate-one-recipe"]}
# Rebuild a single recipe using the python script
rebuild-recipe = "python src/repror/rebuild_recipe.py"

[dependencies]
python = "~=3.10"
matplotlib = "*"
rattler-build = "*"
pyyaml = "*"
pytest = "*"

[pypi-dependencies]
repror = { path = ".", editable = true }
conda-recipe-manager = { git = "https://github.com/conda-incubator/conda-recipe-manager.git" }
