context:
  version: 7.6.0
  name: oauth2-proxy

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/oauth2-proxy/oauth2-proxy/archive/v${{ version }}.tar.gz
    sha256: 2beac9e817d59b37f2277efefeda68447418355792a60da709a80c278628fcd8

build:
  number: 0
  script:
    # - pushd ${{ pkg_src }}
    - if: not win
      then: GOBIN=$(go env GOBIN)
    - if: win
      then: "FOR /F \"delims=\" %%i IN ('go env GOBIN') DO set \"GOBIN=%%i\""
    - if: unix
      then: go build -v -o $GOBIN/${{ name }} .
    - if: win
      then: go build -v -o %GOBIN%\${{ name }}.exe .

requirements:
  build:
    - ${{ compiler('go-nocgo') }}

tests:
  - requirements:
      run:
        - if: win
          then: m2-bash
        - if: win
          then: m2-coreutils
    script:
      - oauth2-proxy --version

about:
  license: MIT
  summary: A reverse proxy and static file server that provides authentication using Providers (Google, GitHub, and others) to validate accounts by email, domain or group.
  homepage: https://github.com/oauth2-proxy/${{ name }}
  repository: https://github.com/oauth2-proxy/${{ name }}
  documentation: https://oauth2-proxy.github.io/oauth2-proxy/

extra:
  recipe-maintainers:
    - asford
    - mxr-conda
    - rluria14
    - ndmaxar
    - oblute
    - RyanHackney
