# test to force the test env creation
# if any dependency is missing the test env creation will fail

package:
  name: r
  version: ${{ r_base }}

build:
  number: 1007
  noarch: generic

requirements:
  host:
    - r-base
  run:
    - r-base
    - r-recommended

tests:
  - script:
      - if: not win
        then: "$R -e \"library('MASS')\""
      - if: win
        then: "\"%R%\" -e \"library('MASS')\""

about:
  license: GPL-3.0-only
  summary: R is a free software environment for statistical computing and graphics.
  # license_file: ${{ env.get("PREFIX") }}/lib/R/share/licenses/GPL-3
  homepage: http://www.r-project.org/

extra:
  recipe-maintainers:
    # N.B., this is the master list of users who (aside from conda-forge/core) maintain R packages across conda-forge. Edit with care!
    - johanneskoester
    - bgruening
    - daler
    - cbrueffer
    - dbast
    - dpryan79
    - mfansler
