
context:
  version: 4.33

recipe:
  name: libev
  version: ${{ version }}

source:
  url: http://dist.schmorp.de/libev/Attic/libev-${{ version }}.tar.gz
  sha256: 507eb7b8d1015fbec5b935f34ebed15bf346bed04a11ab82b8eee848c4205aea

build:
  number: 2
  skip:
    - win

outputs:
  - package:
      name: libev
    build:

      script: 
      - if: unix
        then: install.sh

    requirements:
      build:
      - libtool
      - if: unix
        then: make
      - if: unix
        then: libtool
      - ${{ compiler('c') }}
      run_exports:
        - ${{ pin_subpackage('libev', upper_bound='x.x') }}
    tests:
      - script:
          - "test -f \"${PREFIX}/include/ev.h\""
          - "test -f \"${PREFIX}/include/ev++.h\""
          - "test ! -f \"${PREFIX}/include/event.h\""
          - "test ! -f \"${PREFIX}/lib/libev.a\""
          - if: unix
            then: "test -f \"${PREFIX}/lib/libev${SHLIBEXT}\""
    
  - package:
      name: libev-static
    build:
      script: 
      - if: unix
        then: install.sh
    requirements:
      build:
        - libtool
        - if: unix
          then: make
        - ${{ compiler('c') }}
      host:
        - ${{ pin_subpackage('libev', exact=True) }}
      run:
        - ${{ pin_subpackage('libev', exact=True) }}
    tests:
      - script:
        - "test ! -f \"${PREFIX}/include/event.h\""
        - "test -f \"${PREFIX}/lib/libev.a\""
        requirements:
            run:
              - ${{ pin_subpackage('libev', exact=True) }}
      
  # Compatibility wrapper to enable programs which use the libevent event loop to link against libev
  # Split into a separate package to prevent clobbering libevent
  - package:
      name: libev-libevent
    build:
      script: 
      - if: unix
        then: install.sh
    requirements:
      build:
        - libtool
        - if: unix
          then: make
        - ${{ compiler('c') }}
      host:
        - ${{ pin_subpackage('libev', exact=True) }}
      run:
        - ${{ pin_subpackage('libev', exact=True) }}
      run_constraints:
        - libevent ==9999999999
    tests:
      - script:
          - "test -f \"${PREFIX}/include/event.h\""
    

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: A full-featured and high-performance event loop that is loosely modeled after libevent, but without its limitations and bugs.
  homepage: http://software.schmorp.de/pkg/libev.html

extra:
  recipe-maintainers:
    - petercable
    - carlodri
    - wolfv
