context:
  version: 1.3.10

package:
  name: rasterio
  version: ${{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/${{ version }}.tar.gz
  sha256: 0da4bea271a7f2ef2c44f528245a4f5c76ec635d075a0bd834300c75924b62c5
  patches:
    - gh2704_numpy2.patch
    - gh2805_numpy2.patch
    - gh3091_gdal39.patch

build:
  # skip: true  # [py<38 or ppc64le]
  number: 4
  python:
    entry_points:
      - rio = rasterio.rio.main:main_group

requirements:
  build:
    # - python                                 # [build_platform != target_platform]
    # - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    # - cython                                 # [build_platform != target_platform]
    # - numpy                                  # [build_platform != target_platform]
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python >3.8
    - pip
    - cython
    - numpy
    - libgdal
    - proj
  run:
    - python
    - setuptools >=0.9.8
    - libgdal
    - affine
    - attrs
    - certifi
    - click >=4
    - cligj >=0.5
    # - importlib-metadata  # [py<310]
    - snuggs >=1.4.1
    - click-plugins
    - proj

tests:
  # source_files:
  #   - tests
  # requires:
  #   - pip
  #   # awaiting upstream pytest=8 support
  #   - pytest >=2.8.2,<8
  #   - pytest-cov >=2.2.0
  #   - ipython >=2.0
  #   - boto3 >=1.2.4
  #   - matplotlib-base
  #   - packaging
  #   - hypothesis
  #   - shapely
  # files:
    # - test_data/test.tif
    # imports:
    # - rasterio
  - script:
      - rio --help
  - python:
      imports:
        - rasterio
  
about:
  homepage: https://github.com/rasterio/rasterio
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Rasterio reads and writes geospatial raster datasets

extra:
  recipe-maintainers:
    - weiji14
    - ocefpaf
    - ceholden
    - snowman2
    - xylar
    - akrherz
