context:
  version: 0.9.10

package:
  name: libunistring
  version: ${{ version }}

source:
  url: http://ftpmirror.gnu.org/libunistring/libunistring-${{ version }}.tar.xz
  sha256: eb8fb2c3e4b6e2d336608377050892b54c3c983b646c561836550863003c05d7
  file_name: libunistring-${{ version }}.tar.xz

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - if: unix
      then: gnuconfig
    - ${{ compiler('c') }}
    - make
  host:
  run_exports:
    - ${{ pin_subpackage('libunistring', lower_bound='x', upper_bound='x') }}

tests:
  - script:
      - if: linux
        then: test -e $PREFIX/lib/libunistring.so
      - if: osx
        then: test -e $PREFIX/lib/libunistring.a
      - if: osx
        then: test -e $PREFIX/lib/libunistring.dylib

about:
  license: GPL-3.0-only OR LGPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LIB
  summary: This library provides functions for manipulating Unicode strings and for manipulating C strings according to the Unicode standard.
  homepage: https://www.gnu.org/software/libunistring

extra:
  recipe-maintainers:
    - stefan-balke
    - bgruening
