schema_version: 1

context:
  version: 4.2.3

package:
  name: jupyterlab
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab/jupyterlab-${{ version }}.tar.gz
  sha256: df6e46969ea51d66815167f23d92f105423b7f1f06fa604d4f44aeb018c82c7b

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - jupyter-lab = jupyterlab.labapp:main
      - jupyter-labextension = jupyterlab.labextensions:main
      - jupyter-labhub = jupyterlab.labhubapp:main
      - jlpm = jupyterlab.jlpmapp:main

requirements:
  host:
    - python-build
    - hatch-jupyter-builder >=0.3.2
    - hatchling >=1.21.1
    - pip
    - python >=3.8
  run:
    - async-lru >=1.0.0
    - httpx >=0.25.0
    - importlib_metadata >=4.8.3
    - importlib_resources >=1.4
    - ipykernel >=6.5.0
    - jinja2 >=3.0.3
    - jupyter_core
    - jupyter_server >=2.4.0,<3
    - jupyter-lsp >=2.0.0
    - jupyterlab_server >=2.27.1,<3
    - notebook-shim >=0.2
    - packaging
    - python >=3.8
    - setuptools >=40.1.0
    - tomli >=1.2.2
    - tornado >=6.2.0
    - traitlets

tests:
  - python:
      imports:
        - jupyterlab
  - requirements:
      run:
        - nodejs >=20,<21
        - pip
        - if: win
          then: m2-grep
    script:
      - pip check
      - jupyter lab --version
      - jlpm --version
      - jupyter labextension list
      - jupyter lab licenses
      - jupyter lab path
      - jupyter server extension list
      - jupyter server extension list 1>server_extensions 2>&1
      # - "grep -iE \"jupyterlab.*{{ version | replace(\".\", \"\\\\.\") }}.*OK\" server_extensions"
      - jupyter lab build --dev-build=False --minimize=False
      - jupyter lab clean

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab/static/third-party-licenses.json
  summary: >
    An extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture.
  description: >
    JupyterLab is the next-generation user interface for Project Jupyter. It offers all the familiar building blocks of the classic Jupyter Notebook (notebook, terminal, text editor, file browser, rich outputs, etc.) in a flexible and powerful user inteface. Eventually, JupyterLab will replace the classic Jupyter Notebook.

    JupyterLab can be extended using extensions that are npm packages and use our public APIs. You can search for the GitHub topic or npm keyword `jupyterlab-extension` to find extensions. To learn more about extensions, see our user documentation.

    JupyterLab is suitable for general usage. For JupyterLab extension developers, the extension APIs will continue to evolve.


  homepage: https://github.com/jupyterlab/jupyterlab
  repository: https://github.com/jupyterlab/jupyterlab
  documentation: https://jupyterlab.readthedocs.io

extra:
  recipe-maintainers:
    - krassowski
    - afshin
    - blink1073
    - bollwyvl
    - ellisonbg
    - fcollonval
    - ian-r-rose
    - jasongrout
    - jochym
    - jtpio

