context:
  name: polars
  version: 0.20.31

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/polars-${{ version }}.tar.gz
    sha256: 00f62dec6bf43a4e2a5db58b99bf0e79699fe761c80ae665868eaea5168f3bbb

build:
  number: 0
  skip:
    - "win and python_impl==\"pypy\""

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    # there is no cross-python for linux-64 -> win-64
    - if: "build_platform != target_platform and not target_platform == \"win-64\""
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: crossenv
    - if: build_platform != target_platform
      then: maturin >=1.2.1,<2
    - ${{ compiler('c') }}
    - if: win
      then: ${{ compiler('cxx') }}
    # clang_win-64 already adds all required run_exports for the windows build
    # - if: "not (build_platform == \"linux-64\" and target_platform == \"win-64\")"
    #   then: ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - if: "build_platform == \"win-64\""
      then: posix
    - cmake
    - if: unix
      then: make
    - if: "build_platform != target_platform and target_platform == \"win-64\""
      then: cargo-feature
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.2.1,<2
  run:
    - python
    - numpy >=1.16.0
    - if: py<39
      then: backports.zoneinfo
    - if: py<311
      then: typing_extensions >=4.0.0
    - if: py>=310
      then: packaging

tests:
  - python:
      imports:
        - polars
  - requirements:
      run:
        - pip
    script:
      - "python -c \"from polars import DataFrame\""

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
  homepage: https://github.com/pola-rs/polars
  repository: https://github.com/pola-rs/polars
  documentation: https://pola-rs.github.io/polars-book/user-guide/index.html

extra:
  recipe-maintainers:
    - borchero
    - Maxyme
    - timkpaine
    - ritchie46
    - sugatoray
    - xhochy
    - dhirschfeld
    - pavelzw
    - 48762
