context:
  pkg_name: lz4-c
  name: lz4
  version: 1.9.4

recipe:
  name: ${{ pkg_name }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 0b0e3aa07c8c063ddf40b082bdf7e37a1562bda40a0ff5272957f3e987e0e54b

build:
  number: 0


outputs:
  - package:
      name: lz4-c
    # build:
      # https://abi-laboratory.pro/index.php?view=timeline&l=lz4
    requirements:
      build:
          - ${{ compiler('c') }}
          - if: not win
            then: ${{ compiler('cxx') }}
          - if: not win
            then: make
          - if: unix
            then: patch
          - if: win
            then: m2-patch
          - if: win
            then: m2-gcc-libs

      run_exports:
        - ${{ pin_subpackage(lz4-c, upper_bound='x.x') }}
    tests:
      - requirements:
          run:
            - if: unix
              then: pkg-config
        script:
          - lz4 -h
          - if: unix
            then: lz4c -h
          - if: unix
            then: lz4cat -h
          - if: unix
            then: unlz4 -h
          - if: unix
            then: test -f ${PREFIX}/include/lz4.h
          - if: unix
            then: test -f ${PREFIX}/include/lz4hc.h
          - if: unix
            then: test -f ${PREFIX}/include/lz4frame.h
          - if: win
            then: if not exist %LIBRARY_INC%\\lz4.h exit 1
          - if: win
            then: if not exist %LIBRARY_INC%\\lz4hc.h exit 1
          - if: win
            then: if not exist %LIBRARY_INC%\\lz4frame.h exit 1
          - if: unix
            then: test ! -f ${PREFIX}/lib/liblz4.a
          - if: osx
            then: test -f ${PREFIX}/lib/liblz4.dylib
          - if: linux
            then: test -f ${PREFIX}/lib/liblz4.so
          - if: win
            then: if not exist %LIBRARY_BIN%\\liblz4.dll exit 1
          - if: win
            then: if not exist %LIBRARY_LIB%\\liblz4.lib exit 1
          - if: win
            then: if exist %LIBRARY_LIB%\\liblz4_static.lib exit 1
          - if: unix
            then: test -f ${PREFIX}/lib/pkgconfig/liblz4.pc
          - if: unix
            then: pkg-config --cflags --libs liblz4
  - package:
      name: lz4-c-static
    build:
      script: 
        - if: unix
          then: build_static.sh
        - if: win
          then: bld_static.bat
      
    tests:
      - script:
          - if: unix
            then: test -f ${PREFIX}/lib/liblz4.a
          - if: win
            then: if not exist %LIBRARY_LIB%\\liblz4_static.lib exit 1

about:
  license: BSD-2-Clause
  license_file: lib/LICENSE
  summary: Extremely Fast Compression algorithm
  description: |
    LZ4 is lossless compression algorithm, providing compression speed at 400
    MB/s per core (0.16 Bytes/cycle). It features an extremely fast decoder,
    with speed in multiple GB/s per core (0.71 Bytes/cycle). A high compression
    derivative, called LZ4_HC, is available, trading customizable CPU time for
    compression ratio. LZ4 library is provided as open source software using a
    BSD license.


  homepage: https://www.lz4.org

extra:
  recipe-maintainers:
    - mingwandroid
    - rmax
    - wesm
    - xhochy
