schema_version: 1

context:
  version: 5.2.2

package:
  name: giflib
  version: ${{ version }}

source:
  - url: https://downloads.sourceforge.net/project/giflib/giflib-${{ version }}.tar.gz
    sha256: be7ffbd057cadebe2aa144542fd90c6838c6a083b5e8a9048b8ee3b66b29d5fb
    patches:
      - if: win
        then: fix_win.patch
      - if: win
        then: stdbool_h.patch
  # add a getopt polyfill
  - path: getopt.h  # [win]

build:
  number: 0
  skip:
    - win and vc<14

requirements:
  build:
    - ${{ compiler('c') }}
    - if: not win
      then: make
    - if: win
      then: git
    - cmake
  run_exports:
    - ${{ pin_subpackage('giflib', upper_bound='x.x') }}

tests:
  - script:
      - gif2rgb -h
      - gifbuild -h
      - giffix -h
      - giftext -h
      - gifclrmp -h

about:
  license: MIT
  license_file:
    - COPYING
    - if: win
      then: getopt_LICENSE.txt
  summary: Library for reading and writing gif images
  homepage: http://giflib.sourceforge.net

extra:
  recipe-maintainers:
    - ocefpaf
    - 183amir
    - msarahan
    - isuruf
    - wolfv
    - katietz
