schema_version: 1

context:
  version: 3.7.9
  major_minor: "\"\".\".join(version | split(\".\")[:2])\""

package:
  name: gnutls
  version: ${{ version }}

source:
  url: https://www.gnupg.org/ftp/gcrypt/gnutls/v3.7/gnutls-${{ version }}.tar.xz
  sha256: aaa03416cdbd54eb155187b359e3ec3ed52ec73df4df35a0edd49429ff64d844
  patches:
    # https://gitlab.com/gnutls/gnutls/-/issues/660
    - correct_ssl_test.patch
    # https://gitlab.com/gnutls/gnutls/-/merge_requests/1794
    - 1794_specify_osstatus_error_signature.patch

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - if: osx
      then: gettext >=0.19.8.1
    - libidn2
    - nettle
    - libtasn1
    - p11-kit
    # Test only dependencies
    - if: linux
      then: datefudge
    - gmp
  run_exports:
    - ${{ pin_subpackage('gnutls', upper_bound='x.x') }}
  # ignore_run_exports:
  #   - gmp

tests:
  - script:
      - if: unix
        then: test -f ${PREFIX}/lib/libgnutls${SHLIB_EXT}
      - if: unix
        then: test -f ${PREFIX}/lib/libgnutlsxx${SHLIB_EXT}

about:
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: GnuTLS is a secure communications library implementing the SSL, TLS and DTLS protocols
  homepage: http://www.gnutls.org/index.html
  repository: https://gitlab.com/gnutls/gnutls/tree/master
  documentation: http://www.gnutls.org/documentation.html

extra:
  recipe-maintainers:
    - sachalau
    - sdvillal
    - scopatz
    - hmaarrfk
