{% set name = "mold" %}
{% set version = "2.32.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rui314/mold/archive/v{{ version }}.tar.gz
  sha256: 4b7e4146ea0f52be9adae8b417399f3676a041e65b55e3f25f088120d30a320b

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja

  host:
    - mimalloc  # [not osx]
    - openssl  # [not osx]
    - tbb-devel
    - zlib
    - zstd

test:
  commands:
    - mold --version

about:
  home: https://github.com/rui314/mold
  license: MIT
  license_file: LICENSE
  summary: A Modern Linker

extra:
  recipe-maintainers:
    - apmorton
