schema_version: 1

context:
  version: 2.37

package:
  name: font-ttf-dejavu-sans-mono
  version: ${{ version }}

source:
  url: https://sourceforge.net/projects/dejavu/files/dejavu/${{ version }}/dejavu-sans-ttf-${{ version }}.zip
  sha256: 2c729a21ec4a6c2386f335fbabf64d2c76c0ab758ba54d93efcb09b412e42032

build:
  number: 0
  noarch: generic

tests:
  - requirements:
      run:
        - bzip2
    script:
      - if: unix
        then: test -f ${PREFIX}/fonts/DejaVuSans.ttf

about:
  summary: Monospace font for pretty code listings with many mathematical and other symbols
  description: |
    DejaVu fonts are a font family based on the Vera Fonts. Its purpose is to provide a
    wider range of characters while maintaining the original look and feel through the
    process of collaborative development Monospace font for pretty code listings.
    Next to that, DejaVu contains a lot of mathematical and other symbols, arrows, braille
    patterns, etc
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://dejavu-fonts.github.io/

extra:
  recipe-maintainers:
    - dbast
