name: Building and Rebuilding

on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

env:
  RATTLER_BUILD_ENABLE_GITHUB_INTEGRATION: true

jobs:
  generate-recipes:
    runs-on: ubuntu-latest
    outputs:
      recipes: ${{ steps.generate-matrix.outputs.recipes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - name: Generate matrix
        id: generate-matrix
        run: |
          message=$(pixi r generate-recipes)
          echo $message
          echo "recipes=$message" >> $GITHUB_OUTPUT

  build-and-rebuild-recipes:
    needs: generate-recipes
    continue-on-error: true
    strategy:
      matrix:
        recipes: ${{ fromJson(needs.generate-recipes.outputs.recipes) }}
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      # - name: Set timezone to UTC
      #   run: sudo timedatectl set-timezone UTC

      # - name: Set LANG
      #   run: echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

      # - name: Verify LANG for Initial Build
      #   run: echo $LANG

      - name: Build recipes and track if hash is equal
        run: |
          pixi run build-recipe ${{ matrix.recipes }}

      # - name: Set timezone to PST
      #   run: sudo timedatectl set-timezone America/Los_Angeles

      # - name: Set LANG
      #   run: echo "LANG=et_EE.UTF-8" >> $GITHUB_ENV

      # - name: Verify LANG for Initial Build
      #   run: echo $LANG

      - name: Rebuild recipes and track if hash is equal
        run: |
          pixi run rebuild-recipe ${{ matrix.recipes }}

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: build-info
          path: |
            build_info/
            ci_artifacts/

  statistics:
    runs-on: ubuntu-latest
    needs: build-and-rebuild-recipes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"

      - uses: actions/download-artifact@v3
        with:
          name: build-info
          path: .

      - run: |
          ls -la build_info/

      - name: Calculate statistics and plot output
        run: |
          pixi run python src/repror/rewrite_readme.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/history.json
          git add data/chart.png
          git add README.md
          git commit -m "Update README.md with latest build statistics"
          git push
